Repository wecode-bootcamp-korea/36-2nd-5MILLION-frontend, pull requests merged in 2022-09, with the labels that each got.

#2 [36기 이주영] ADD: complete nav UI
  src/components/Nav/Nav.js
  src/index.js
  src/styles/GlobalStyle.js
Labels: 멘토 리뷰 요청

#4 [36기 김준호] ADD: instructor UI [통신까지 마무리]
  package-lock.json
  package.json
  src/pages/Instructor/Instructor.js
  src/pages/Instructor/Styled.Instructor.js
  src/styles/GlobalStyle.js
Labels: 완료

#9 [36기 김준호] ADD: main UI 구현[완료]
  package-lock.json
  package.json
  public/data/img/img.json
  src/pages/Main/Carousel/Carousel.js
  src/pages/Main/Carousel/Styled.Carousel.js
  src/pages/Main/Main.js
  src/pages/Main/Styled.Main.js
Labels: 완료

#8 [36기 이주영] ADD: completed button function and add modal
  public/data/data.json
  src/components/Modal/Modal.js
  src/pages/Schedule/Calender/Date/Class/Class.js
  src/pages/Schedule/StyledSchedule.js
  src/styles/variable.js
Labels: 완료

#6 [36기 김준호] ADD: Detail UI #4
  public/data/detail/detail1.json
  public/data/detail/detail2.json
  public/data/detail/schedule/schedule.json
  src/pages/InstructorDetail/InstructorDetail.js
  src/pages/InstructorDetail/ScheduleBox/ScheduleBox.js
  src/pages/InstructorDetail/ScheduleBox/Styled.ScheduleBox.js
  src/pages/InstructorDetail/Styled.InstructorDetail.js
Labels: 완료

#7 [36기 이주영] ADD: Completed filter UI in schedule page
  src/components/Nav/Nav.js
  src/pages/Schedule/Calender/Calender.js
  src/pages/Schedule/Calender/Date/Class/Class.js
  src/pages/Schedule/Dropdown.js
  src/pages/Schedule/Schedule.js
  src/pages/Schedule/StyledSchedule.js
Labels: 완료

#10 [36기 김준호] ADD: main UI 구현, 통신까지 구현완료
  src/pages/Main/Carousel/Carousel.js
  src/pages/Main/Carousel/Styled.Carousel.js
  src/pages/Main/Main.js
  src/pages/Main/Styled.Main.js
Labels: 완료

#12 [36기 이주영] ADD : complete carousel function at A Calender
  public/data/data.json
  src/components/Modal/Modal.js
  src/components/Nav/Nav.js
  src/pages/Schedule/Calender/Calender.js
  src/pages/Schedule/Calender/Date/Class/Class.js
  src/pages/Schedule/Calender/Date/Day.js
  src/pages/Schedule/Dropdown.js
  src/pages/Schedule/Schedule.js
  src/pages/Schedule/StyledSchedule.js
Labels: Conflict 해결 요청

#13 [36기 김준호] ADD:detail Page 통신 완료
  public/data/detail/schedule/origin.json
  src/pages/InstructorDetail/InstructorDetail.js
  src/pages/InstructorDetail/ScheduleBox/ScheduleBox.js
  src/pages/InstructorDetail/ScheduleBox/Styled.ScheduleBox.js
Labels: 멘토 리뷰 요청

#5 [36기 송경용] ADD: sidebar UI
  .gitignore
  package-lock.json
  package.json
  src/Router.js
  src/components/Footer/Styled.Footer.js
  src/components/Modal/Modal.js
  src/components/Nav/Nav.js
  src/components/SideBar/Menu/Menu.js
  src/components/SideBar/Menu/Styles.Menu.js
  src/components/SideBar/MyAccount/MyAccount.js
  src/components/SideBar/MyAccount/Styles.MyAccount.js
  src/components/SideBar/SideBar.js
  src/components/SideBar/SignIn/KakaoRedirectHandler.js
  src/components/SideBar/SignIn/OAuth.js
  src/components/SideBar/SignIn/SignIn.js
  src/components/SideBar/SignIn/Styles.SignIn.js
  src/components/SideBar/Styles.SideBar.js
  src/pages/Aside/Aside.js
  src/pages/InstructorDetail/Styled.InstructorDetail.js
  src/pages/Main/Styled.Main.js
  src/pages/Schedule/Calender/Calender.js
  src/pages/Schedule/Calender/Date/Class/Class.js
  src/pages/Schedule/Calender/Date/Day.js
  src/pages/Schedule/Dropdown.js
  src/pages/Schedule/Schedule.js
  src/pages/Schedule/StyledSchedule.js
  src/styles/GlobalStyle.js
Labels: 멘토 리뷰 요청

#15 소셜 로그인 마무리,,
  src/components/SideBar/Menu/Menu.js
  src/components/SideBar/SideBar.js
  src/components/SideBar/SignIn/KakaoRedirectHandler.js
  src/components/SideBar/SignIn/OAuth.js
  src/components/SideBar/SignIn/SignIn.js
Labels: 완료
